services:
  demo-api-app:
    image: demo-api:0.0.1
    container_name: demo-api-app
    networks:
      - bootcamp-network
    ports:
      - "8182:8082"

  demo-calculator-app:
    image: demo-calculator:0.0.1
    container_name: demo-calculator-app
    networks:
      - bootcamp-network
    ports:
      - "8181:8081"

  demo-helloworld-app:
    image: demo-helloworld:0.0.1
    container_name: demo-helloworld-app
    networks:
      - bootcamp-network
    ports:
      - "8180:8080"

  postgres:
    image: postgres:15
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: bootcamp_2504p
      PGDATA: /var/lib/postgresql/data/pgdata15
    networks:
      - bootcamp-network
    ports:
      - "5532:5432"
    volumes:
      - "./pgdata:/var/lib/postgresql/data/pgdata"

  redis:
    image: redis:7
    container_name: redis-container
    networks:
      - bootcamp-network
    ports:
      - "6479:6379"
    volumes:
      - "./redis_data:/data"

volumes:
  redis_data:

networks:
  bootcamp-network:
    driver: bridge