spring:
  datasource:
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://postgres-container:5432/bootcamp_2504p"
    username: "postgres"
    password: "admin1234"
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
  data:
    redis:
      host: "redis-container"
      port: 6379
      database: 0
      timeout: 2000

service-api:
  jsonplaceholder:
    host: "jsonplaceholder.typicode.com"
    endpoints: 
      users: "/users"
      posts: "/posts"
      comments: "/comments"

server:
  port: 8082
