FROM openjdk:21
LABEL maintainer="itsupport@gmail.com"
ADD target/demo-calculator-0.0.1-SNAPSHOT.jar demo-calculator-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "demo-calculator-0.0.1-SNAPSHOT.jar"]
EXPOSE 8081